---
- name: Migrate from nftables back to UFW
  hosts: all
  become: yes
  vars_files:
    - ~/.slv/versions.yml
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Enable UFW and set default policies
      ufw:
        state: enabled
        direction: incoming
        policy: deny

    - name: Allow SSH for multiple IPs
      ufw:
        rule: allow
        name: OpenSSH
        from_ip: "{{ item }}"
      loop: "{{ mainnet_validators.allowed_ssh_ips }}"
      when: mainnet_validators.allowed_ssh_ips is defined

    - name: Allow 2 UDP ports from each IP in allowed_ips
      ufw:
        rule: allow
        port: "11228,11229"
        proto: udp
        from_ip: "{{ item }}"
      loop: "{{ mainnet_validators.allowed_ips }}"
      when: mainnet_validators.allowed_ips is defined

    - name: Allow 1 TCP port from each IP in allowed_ips
      ufw:
        rule: allow
        port: "11226"
        proto: tcp
        from_ip: "{{ item }}"
      loop: "{{ mainnet_validators.allowed_ips }}"
      when: mainnet_validators.allowed_ips is defined

    - name: Reload UFW to apply all rules
      command: ufw reload
