---
- name: Setup Firedancer
  hosts: all
  become: true
  become_user: solv
  tasks:
    - name: Clone Firedancer repository
      git:
        repo: https://github.com/firedancer-io/firedancer.git
        dest: /home/solv/firedancer
        update: yes
        force: yes
        version: v{{ hostvars[inventory_hostname].version }}

    - name: Initialize git submodules
      command: git submodule update --init --recursive
      args:
        chdir: /home/solv/firedancer

    - name: Run deps.sh script with yes (async/poll)
      shell: |
        sudo apt update -y
        yes y | ./deps.sh
      args:
        chdir: /home/solv/firedancer
      async: 300 # wait for 5 minutes
      poll: 15 # check every 15 seconds
      register: deps_result
      until: deps_result.rc == 0
      retries: 3
      delay: 10

    - name: Build Firedancer with make
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        . $HOME/.cargo/env
        make -j fdctl solana
      args:
        chdir: /home/solv/firedancer
        executable: /bin/bash
      register: build_result
      until: build_result.rc == 0
      retries: 3
      delay: 10

    - name: Create symbolic link for fdctl
      shell: sudo ln -s /home/solv/firedancer/build/native/gcc/bin/fdctl /usr/local/bin/fdctl
      args:
        creates: /usr/local/bin/fdctl

    - name: Create config.toml
      template:
        src: ~/.slv/testnet-validator/firedancer-config.toml.j2
        dest: /home/solv/firedancer/firedancer-config.toml
        owner: solv
        group: solv
        mode: '0644'

    - name: Generate start-firedancer.sh from template
      template:
        src: ~/.slv/testnet-validator/start-firedancer.sh.j2
        dest: /home/solv/start-firedancer.sh
        mode: '0755'
        owner: solv
        group: solv
      vars:
        vote_account: '{{ hostvars[inventory_hostname].vote_account }}'

    - name: Create Firedancer systemd service file with sudo tee
      shell: |
        echo "[Unit]
        Description=Firedancer Solana
        After=network.target
        StartLimitIntervalSec=0

        [Service]
        Type=simple
        Restart=always
        RestartSec=1
        User=solv
        LimitNOFILE=1000000
        LogRateLimitIntervalSec=0
        ExecStart=/home/solv/start-firedancer.sh

        [Install]
        WantedBy=multi-user.target" | sudo tee /etc/systemd/system/firedancer.service > /dev/null
      become: yes
      become_user: solv

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      become: yes
      become_user: root

    - name: Enable Firedancer
      shell: sudo systemctl enable firedancer
      become: yes
      become_user: root
