---
- name: Run Command
  hosts: all
  become: true
  gather_facts: no
  become_user: solv
  tasks:
    - name: Start Firedancer
      shell: . ~/.profile && sudo systemctl start firedancer
      register: command_output

    - name: Ensure /mnt directory has correct permissions
      shell: sudo chown -R solv:solv /mnt && sudo chmod -R 700 /mnt
      become: true
      become_user: solv

    - name: Display Command output
      debug:
        msg: '{{ inventory_hostname }} ({{ hostvars[inventory_hostname].name }}): Start Firedancer: {{ command_output.stdout }}'
