---
- name: Install Rust and Cargo for solv user
  hosts: all
  become: true
  vars:
    rustup_url: 'https://sh.rustup.rs'
  tasks:
    - name: Download and install Rust using rustup
      shell: |
        curl {{ rustup_url }} -sSf | sh -s -- -y
      args:
        executable: /bin/bash
      become: false
      become_user: solv

    - name: Set ownership for .cargo directory
      file:
        path: /home/solv/.cargo
        state: directory
        owner: solv
        group: solv
        recurse: yes

    - name: Add Cargo to PATH in .profile
      lineinfile:
        path: /home/solv/.profile
        line: 'export PATH="$HOME/.cargo/env:$PATH"'
        state: present

    - name: Set ownership of .profile
      file:
        path: /home/solv/.profile
        owner: solv
        group: solv
        mode: '0644'

    - name: Source Cargo environment
      shell: |
        source /home/solv/.cargo/env
      args:
        executable: /bin/bash
      become: false
      become_user: solv

    - name: Add rustfmt component
      shell: |
        source /home/solv/.cargo/env && rustup component add rustfmt
      args:
        executable: /bin/bash
      become: false
      become_user: solv

    - name: Update Rust
      shell: |
        source /home/solv/.cargo/env && rustup update
      args:
        executable: /bin/bash
      become: false
      become_user: solv
