---
- name: Copy validator and vote key pairs
  hosts: all
  gather_facts: no
  vars_files:
    - ~/.slv/config.validator.testnet.yml

  tasks:
    - name: Select node config by identity_account
      set_fact:
        validators: >-
          {{
            validators
            | selectattr('identity_account', 'equalto', hostvars[inventory_hostname].identity_account)
            | list
            | first
          }}

    - name: Copy validator key file
      become: yes
      become_user: root
      copy:
        src: "~/.slv/keys/{{ validators.identity_account }}.json"
        dest: "/home/solv/testnet-validator-keypair.json"
        owner: solv
        group: solv
        mode: "0600"

    - name: Copy vote key file
      become: yes
      become_user: root
      copy:
        src: "~/.slv/keys/{{ validators.vote_account }}.json"
        dest: "/home/solv/testnet-vote-account-keypair.json"
        owner: solv
        group: solv
        mode: "0600"
