---
- name: Deploy start-validator script dynamically
  hosts: all
  become: true
  vars_files:
    - ~/.slv/inventory.testnet.validators.yml
  tasks:
    - name: Ensure /home/solv exists
      file:
        path: /home/solv
        state: directory
        owner: solv
        group: solv
        mode: '0755'

    - name: Generate start-validator.sh from template
      template:
        src: templates/start-validator.sh.j2
        dest: /home/solv/start-validator.sh
        mode: '0755'
        owner: solv
        group: solv
      vars:
        vote_account: '{{ hostvars[inventory_hostname].vote_account }}'
      when: matched_validator is defined

    # Make sure if solv user has permission for /mnt directory
    - name: Ensure /mnt directory belongs to solv
      file:
        path: /mnt
        state: directory
        owner: solv
        group: solv
        mode: '0755'
