---
- name: Deploy start-validator script dynamically
  hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: Check if host name is agave
      debug:
        msg: "Skipping tasks because validator_type is not 'agave'"
      when: hostvars[inventory_hostname].validator_type != 'agave'
      ignore_errors: false
      failed_when: hostvars[inventory_hostname].validator_type != 'agave'
      tags: skip_check
  vars_files:
    - ~/.slv/inventory.testnet.validators.yml
  tasks:
    - name: Ensure /home/solv exists
      file:
        path: /home/solv
        state: directory
        owner: solv
        group: solv
        mode: "0755"

    - name: Generate start-validator.sh from template
      template:
        src: ~/.slv/testnet-validator/start-validator.sh.j2
        dest: /home/solv/start-validator.sh
        mode: "0755"
        owner: solv
        group: solv
      vars:
        vote_account: "{{ hostvars[inventory_hostname].vote_account }}"

    # Make sure if solv user has permission for /mnt directory
    - name: Ensure /mnt directory (and its contents) belongs to solv
      file:
        path: /mnt
        state: directory
        owner: solv
        group: solv
        mode: "0755"
        recurse: yes
