---
- name: Start Firedancer Service
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Start Firedancer Service
      systemd:
        name: firedancer
        state: started
      register: command_output
      until: command_output.rc == 0
      retries: 3
      delay: 10

    - name: Display Command output
      debug:
        msg: '{{ inventory_hostname }} ({{ hostvars[inventory_hostname].name }}): Start Firedancer: {{ command_output.stdout }}'
      ignore_errors: yes