---
- name: Switch On Identity
  hosts: "{{ on_host }}"
  become: true
  become_user: solv
  gather_facts: no
  vars:
    key_name: "{{ hostvars[inventory_hostname].identity_account }}.json"
    local_key_path: "~/.slv/{{ key_name }}"

  tasks:
    - name: Read local validator key file securely (base64)
      delegate_to: localhost
      slurp:
        src: "{{ local_key_path }}"
      register: key_file
      no_log: true

    - name: Upload Tower File
      ansible.builtin.copy:
        src: ~/.slv/tower/tower-1_9-{{ hostvars[inventory_hostname].identity_account }}.bin
        dest: /mnt/ledger/tower-1_9-{{ hostvars[inventory_hostname].identity_account }}.bin

    - name: Set Identity to Validator Key via stdin
      shell: . ~/.profile && agave-validator -l /mnt/ledger set-identity
      args:
        stdin: "{{ key_file.content | b64decode }}"
        executable: /bin/bash
      register: set_identity_result
      timeout: 20

    - name: Add Authorized Voter via stdin
      shell: . ~/.profile && agave-validator -l /mnt/ledger authorized-voter add
      args:
        stdin: "{{ key_file.content | b64decode }}"
        executable: /bin/bash
      register: add_voter_result
      timeout: 20
      ignore_errors: yes

    - name: Show set-identity output
      debug:
        msg: "{{ inventory_hostname }}:\n{{ set_identity_result.stdout }}"

    - name: Show authorized-voter output
      debug:
        msg: "{{ inventory_hostname }}:\n{{ add_voter_result.stdout }}"
