---
- name: Switch On Identity
  hosts: "{{ on_host }}"
  become: true
  become_user: solv
  gather_facts: no
  tasks:
    - name: Upload Tower File
      ansible.builtin.copy:
        src: ~/.slv/tower/tower-1_9-{{ hostvars[inventory_hostname].identity_account }}.bin
        dest: /mnt/ledger/tower-1_9-{{ hostvars[inventory_hostname].identity_account }}.bin

    - name: Set Identity to Mainnet Validator Key
      shell: . ~/.profile && agave-validator -l /mnt/ledger set-identity /home/solv/mainnet-validator-keypair.json
      register: command_output
      timeout: 20
      args:
        executable: /bin/bash

    - name: Add Authorized Voter
      shell: . ~/.profile && agave-validator -l /mnt/ledger authorized-voter add /home/solv/mainnet-validator-keypair.json
      register: command_output
      timeout: 20
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Show captured output
      debug:
        msg: "{{ inventory_hostname }}:\n{{ command_output.stdout }}"
