---
- name: Update Startup Config
  hosts: all
  become: true
  become_user: solv
  tasks:
    - name: Create config.toml
      template:
        src: ~/.slv/testnet-validator/firedancer-config.toml.j2
        dest: /home/solv/firedancer/firedancer-config.toml
        owner: solv
        group: solv
        mode: '0644'

    - name: Generate start-firedancer.sh from template
      template:
        src: ~/.slv/testnet-validator/start-firedancer.sh.j2
        dest: /home/solv/start-firedancer.sh
        mode: '0755'
        owner: solv
        group: solv
      vars:
        vote_account: '{{ hostvars[inventory_hostname].vote_account }}'
