---
- name: Run Command
  hosts: all
  become: true
  become_user: solv
  gather_facts: no
  pre_tasks:
    - name: Check if host name is agave
      debug:
        msg: "Skipping tasks because validator_type is not 'agave'"
      when: hostvars[inventory_hostname].validator_type != 'agave'
      ignore_errors: false
      failed_when: hostvars[inventory_hostname].validator_type != 'agave'
      tags: skip_check
  tasks:
    - name: Start Solv
      shell: . ~/.profile && sudo systemctl start solv
      register: command_output

    - name: Display Command output
      debug:
        msg: '{{ inventory_hostname }} ({{ hostvars[inventory_hostname].name }}): Start Solv: {{ command_output.stdout }}'
