---
- name: Set Unstaked Key to Identity
  hosts: all
  become: true
  become_user: solv
  tasks:
    - name: Change Symbolic Link to Unstaked Identity
      shell: ln -sf /home/solv/unstaked-identity.json /home/solv/identity.json
      become: true
      become_user: solv

    - name: Set Identity to Unstaked Key
      shell: . ~/.profile && agave-validator -l /mnt/ledger set-identity /home/solv/unstaked-identity.json
      register: command_output
      timeout: 20
      args:
        executable: /bin/bash
