---
- name: Restart Solana Validator
  hosts: all
  become: true
  become_user: solv
  tasks:
    - name: Restart Solana Node
      shell: . ~/.profile && agave-validator -l /mnt/ledger exit
      register: solana_version_output

    - name: Display Solana Restart Result with name
      debug:
        msg: "{{ inventory_hostname }} ({{ hostvars[inventory_hostname]['name'] }}): Solana Restart Result: {{ solana_version_output.stdout }}"
