---
- name: Install and configure Jupiter Swap API
  hosts: all
  become: true
  vars_files:
    - ~/.slv/versions.yml
  vars:
    working_dir: "/home/solv"
    api_version: "{{ jupiter.api_version }}"
    download_url: "https://github.com/jup-ag/jupiter-swap-api/releases/download"
    service_template: ~/.slv/jupiter/jupiter-api.service.j2
    service_file_path: "/etc/systemd/system/jupiter-api.service"
  tasks:
    - name: Install required packages
      apt:
        name:
          - unzip
          - wget
        state: present

    - name: Download Jupiter Swap API binary
      shell: |
        wget {{ download_url }}/{{ api_version }}/jupiter-swap-api-x86_64-unknown-linux-gnu.zip -O jupiter-swap-api.zip
      args:
        chdir: "{{ working_dir }}"

    - name: Unzip Jupiter Swap API binary
      unarchive:
        src: "{{ working_dir }}/jupiter-swap-api.zip"
        dest: "{{ working_dir }}"
        remote_src: yes

    - name: Set executable permissions and ownership for Jupiter Swap API
      file:
        path: "{{ working_dir }}/jupiter-swap-api"
        mode: "0755"
        owner: solv
        group: solv

    - name: Remove the downloaded zip file
      file:
        path: "{{ working_dir }}/jupiter-swap-api.zip"
        state: absent

    - name: Check if Jupiter API service is running
      shell: systemctl is-active jupiter-api
      register: jupiter_api_status
      failed_when: false

    - name: Stop the Jupiter API service if running
      systemd:
        name: jupiter-api
        state: stopped
      when: jupiter_api_status.stdout == 'active'

    - name: Replace existing Jupiter Swap API binary
      copy:
        src: "{{ working_dir }}/jupiter-swap-api"
        dest: "{{ working_dir }}/jupiter-swap-api"
        remote_src: yes
        mode: "0755"
        owner: solv
        group: solv

    - name: Create the Jupiter API systemd service file
      template:
        src: "{{ service_template }}"
        dest: "{{ service_file_path }}"
        mode: "0644"

    - name: Reload systemd to apply the new service file
      shell: systemctl daemon-reload

    - name: Enable and start the Jupiter API service
      systemd:
        name: jupiter-api
        enabled: yes
        state: started
