---
- name: Setup UFW
  hosts: all
  become: yes
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Enable UFW and set default policies
      ufw:
        state: enabled
        direction: incoming
        policy: deny

    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow ports 8000-8020 TCP
      ufw:
        rule: allow
        port: '8000:8020'
        proto: tcp

    - name: Allow ports 8000-8020 UDP
      ufw:
        rule: allow
        port: '8000:8020'
        proto: udp
