---
# Ansible playbook to set up a build server for SLV
# This playbook installs all the necessary dependencies for building SLV

- name: Setup SLV Build Server
  hosts: build_servers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - build-essential
          - curl
          - unzip
          - git
          - python3
          - python3-pip
        state: present