---
- name: Deploy and configure Solana validator service
  hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: Check if host name is agave
      debug:
        msg: "Skipping tasks because validator_type is not 'agave'"
      when: hostvars[inventory_hostname].validator_type != 'agave'
      ignore_errors: false
      failed_when: hostvars[inventory_hostname].validator_type != 'agave'
      tags: skip_check
  tasks:
    - name: Ensure systemd service directory exists
      file:
        path: /etc/systemd/system
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Deploy solv.service systemd unit file
      template:
        src: ~/.slv/testnet-validator/solv.service.j2
        dest: /etc/systemd/system/solv.service
        owner: root
        group: root
        mode: '0644'

    - name: Ensure /mnt directory has correct permissions
      file:
        path: '/mnt'
        state: directory
        owner: solv
        group: solv
        mode: '0755'

    - name: Reload systemd daemon
      command: systemctl daemon-reload
