---
- name: Run Command
  hosts: all
  become: true
  become_user: solv
  gather_facts: no
  pre_tasks:
    - name: Check if host name is firedancer
      debug:
        msg: "Skipping tasks because validator_type is not 'firedancer'"
      when: hostvars[inventory_hostname].validator_type != 'firedancer'
      ignore_errors: false
      failed_when: hostvars[inventory_hostname].validator_type != 'firedancer'
      tags: skip_check
  tasks:
    - name: Stop Firedancer
      shell: . ~/.profile && sudo systemctl stop firedancer
      register: command_output

    - name: Display Command output
      debug:
        msg: '{{ inventory_hostname }} ({{ hostvars[inventory_hostname].name }}): Stop Firedancer: {{ command_output.stdout }}'
