---
- import_playbook: ../cmn/setup_ufw.yml
- import_playbook: ../cmn/install_package.yml
- import_playbook: ../cmn/install_rust.yml
- import_playbook: ../cmn/install_agave.yml
- import_playbook: ../cmn/mount_disks.yml
- import_playbook: ../cmn/optimize_system.yml
- import_playbook: ../cmn/setup_norestart.yml
- import_playbook: ../cmn/setup-logrotate.yml
- import_playbook: ../cmn/setup-unstaked-identity.yml
- import_playbook: setup_firedancer.yml
- import_playbook: setup_snapshot_finder.yml
- import_playbook: start_firedancer.yml
