---
- name: Load validator type from inventory
  hosts: all
  gather_facts: no
  tasks:
    - name: Set validator type fact for each host
      set_fact:
        validator_type: "{{ validator_type | default('firedancer') }}"
    
    - name: Debug validator type. Stop if not set
      debug:
        msg: "Validator type is {{ validator_type }}"

    - name: Fail if validator type is not set
      fail:
        msg: "Validator type is not set. Please set it in the inventory."
      when: validator_type is not defined

    - name: Initialize Jito Mainnet Validator
      include_tasks: init-jito.yml
      when: validator_type == 'jito'

    - name: Initialize Firedancer Mainnet Validator
      include_tasks: init-firedancer.yml
      when: validator_type == 'firedancer'

