name = "slv-cf-workers-template-contact-email"
main = "./src/index.ts"
compatibility_date = "2025-01-04"
workers_dev = false
compatibility_flags = [ "nodejs_compat_v2"]
route = { pattern = "contact-email-api.slv.dev", custom_domain = true }

[vars]
NODE_ENV = "development"

[observability]
enabled = true